# app/data/models.py

from sqlalchemy import Column, String, Float, DateTime, UniqueConstraint, Integer, Date, Text, Boolean
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import declarative_base
import uuid
from abc import ABC, abstractmethod
from datetime import date
from typing import List
from dataclasses import dataclass
from datetime import datetime
from typing import Dict, Optional

Base = declarative_base()


class MarketOHLC(Base):
    __tablename__ = "market_ohlc"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    symbol = Column(String, nullable=False)
    timestamp = Column(DateTime, nullable=False)
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Float, nullable=False)

    __table_args__ = (
        UniqueConstraint("symbol", "timestamp", name="uix_symbol_timestamp"),
    )


class DecisionLog(Base):
    __tablename__ = "decision_logs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    timestamp = Column(DateTime, nullable=False)
    symbol = Column(String, nullable=False)
    action = Column(String, nullable=False)
    quantity = Column(Float)
    price = Column(Float)
    reasoning = Column(String)
    portfolio_before = Column(String)  # store JSON string
    portfolio_after = Column(String)



@dataclass
class OHLCRecord:
    symbol: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float
    

@dataclass
class MarketState:
    symbol: str
    timestamp: datetime
    latest_price: float
    previous_price: Optional[float]
    indicators: Dict[str, float]
    previous_indicators: Dict[str, float]



class SignalQueue(Base):
    """
    Pending and historical trade signals generated by run_signals.py.
    One row per signal. Status lifecycle: PENDING → PLACED → FILLED / REJECTED / CANCELLED.
    """
    __tablename__ = "signal_queue"

    id           = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    created_at   = Column(DateTime, nullable=False)
    signal_date  = Column(Date, nullable=False)
    symbol       = Column(String, nullable=False)
    action       = Column(String, nullable=False)   # BUY / SELL
    strategy     = Column(String, nullable=False)   # sub-strategy source
    regime_label = Column(String, nullable=True)    # regime at signal time
    weight       = Column(Float,  nullable=True)    # strategy weight at signal time
    raw_price    = Column(Float,  nullable=False)   # close price when signal fired
    target_qty   = Column(Integer, nullable=False)
    status       = Column(String, nullable=False, default="PENDING")
    order_id     = Column(String, nullable=True)
    fill_price   = Column(Float,  nullable=True)
    fill_qty     = Column(Integer, nullable=True)
    notes        = Column(Text,   nullable=True)
    session_id   = Column(String, nullable=True)    # paper session that generated this signal


class LivePosition(Base):
    """
    Current open positions for live/paper trading.
    Persists across daily runs. Reconciled against broker on each signal run.
    """
    __tablename__ = "live_positions"

    symbol         = Column(String,  primary_key=True)
    quantity       = Column(Integer, nullable=False)
    average_price  = Column(Float,   nullable=False)
    entry_date     = Column(Date,    nullable=False)
    strategy       = Column(String,  nullable=False)   # owning sub-strategy
    last_synced_at = Column(DateTime, nullable=False)


class BrokerConnection(Base):
    """
    Stores a user's broker credentials (encrypted) and OAuth token.
    One row per (user_id, broker) pair.

    Supported brokers: 'zerodha'  — extend CHECK constraint in DB when adding more.
    """
    __tablename__ = "broker_connections"

    id               = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id          = Column(UUID(as_uuid=True), nullable=False)
    broker           = Column(String, nullable=False)              # 'zerodha'
    api_key          = Column(String, nullable=False)
    api_secret_enc   = Column(Text,   nullable=False)              # Fernet-encrypted
    access_token_enc = Column(Text,   nullable=True)               # Fernet-encrypted, refreshed daily
    token_fetched_at = Column(DateTime, nullable=True)
    broker_user_id   = Column(String, nullable=True)               # e.g. "ZP1234" from Zerodha
    status           = Column(String, nullable=False, default="connected")
    # status values: 'connected' | 'token_expired' | 'disconnected'
    created_at       = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_at       = Column(DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)

    __table_args__ = (
        UniqueConstraint("user_id", "broker", name="uix_user_broker"),
    )


class MarketDataProvider(ABC):
    """
    Base interface for all market data providers.
    """

    @abstractmethod
    def fetch_ohlc(
        self,
        symbol: str,
        start: date,
        end: date,
        interval: str = "1d"
    ) -> List[OHLCRecord]:
        """
        Fetch OHLC data for a symbol between start and end dates.
        Must return normalized OHLCRecord list.
        """
        pass



