-- =============================================================================
-- Live trading tables — signal_queue and live_positions
-- Run once against the Supabase / PostgreSQL database.
-- Safe to re-run: uses CREATE TABLE IF NOT EXISTS.
--
-- Alternatively, run scripts/init_db.py which calls Base.metadata.create_all()
-- and picks up these models from app/data/models.py automatically.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- signal_queue
-- Stores every signal generated by run_signals.py.
-- Status lifecycle: PENDING → PLACED → FILLED | REJECTED | CANCELLED
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS signal_queue (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at   TIMESTAMP   NOT NULL,
    signal_date  DATE        NOT NULL,
    symbol       VARCHAR     NOT NULL,
    action       VARCHAR     NOT NULL,          -- BUY / SELL
    strategy     VARCHAR     NOT NULL,          -- sub-strategy name
    regime_label VARCHAR,                       -- regime label at signal time
    weight       FLOAT,                         -- strategy weight at signal time
    raw_price    FLOAT       NOT NULL,          -- close price when signal fired
    target_qty   INTEGER     NOT NULL,
    status       VARCHAR     NOT NULL DEFAULT 'PENDING',
    order_id     VARCHAR,                       -- broker order ID after placement
    fill_price   FLOAT,                         -- actual fill price
    fill_qty     INTEGER,                       -- actual fill quantity
    notes        TEXT
);

CREATE INDEX IF NOT EXISTS idx_signal_queue_date_status
    ON signal_queue (signal_date, status);

CREATE INDEX IF NOT EXISTS idx_signal_queue_symbol
    ON signal_queue (symbol);

-- ---------------------------------------------------------------------------
-- live_positions
-- Current open positions. One row per symbol (upserted on BUY, deleted on SELL).
-- Persists across daily runs and is reconciled against broker on each run.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS live_positions (
    symbol          VARCHAR     PRIMARY KEY,
    quantity        INTEGER     NOT NULL,
    average_price   FLOAT       NOT NULL,
    entry_date      DATE        NOT NULL,
    strategy        VARCHAR     NOT NULL,       -- sub-strategy that opened position
    last_synced_at  TIMESTAMP   NOT NULL
);

-- ---------------------------------------------------------------------------
-- selector_state (optional — used by run_signals.py to persist LLM selector)
-- Stores the adaptive selector's rolling history and regime tracking as JSON.
-- One row, updated on each weekly rebalance.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS selector_state (
    id               INTEGER     PRIMARY KEY DEFAULT 1,
    updated_at       TIMESTAMP   NOT NULL,
    confirmed_regime VARCHAR,
    pending_regime   VARCHAR,
    pending_count    INTEGER     NOT NULL DEFAULT 0,
    weights_json     TEXT        NOT NULL,      -- JSON: {"DualMA": 0.25, ...}
    history_json     TEXT        NOT NULL,      -- JSON: [{date, label, ...}, ...]
    last_rebalanced  DATE
);
