-- =============================================================================
-- Migration: Create backend tables in Supabase B (dbptdhnamqtfwvupscia)
-- Run this once in the Supabase B SQL editor (Dashboard → SQL Editor → New query)
-- =============================================================================

-- 1. market_ohlc — OHLCV price history (populated by scripts/ingest_symbols.py)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.market_ohlc (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    symbol      text NOT NULL,
    timestamp   timestamp NOT NULL,
    open        double precision NOT NULL,
    high        double precision NOT NULL,
    low         double precision NOT NULL,
    close       double precision NOT NULL,
    volume      double precision NOT NULL,
    CONSTRAINT uix_symbol_timestamp UNIQUE (symbol, timestamp)
);

-- Index for range queries by symbol+date (used by BacktestEngine and signal generation)
CREATE INDEX IF NOT EXISTS idx_market_ohlc_symbol_ts
    ON public.market_ohlc (symbol, timestamp);

-- market_ohlc is read-only from the frontend; no RLS needed (no user-specific data).
-- If you want to lock it down entirely, enable RLS and add a SELECT-only service-role policy.


-- 2. signal_queue — BUY/SELL signals generated by run_paper_signals.py
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.signal_queue (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at  timestamp NOT NULL,
    signal_date date NOT NULL,
    symbol      text NOT NULL,
    action      text NOT NULL,          -- BUY | SELL
    strategy    text NOT NULL,
    regime_label text,
    weight      double precision,
    raw_price   double precision NOT NULL,
    target_qty  integer NOT NULL,
    status      text NOT NULL DEFAULT 'PENDING',
    order_id    text,
    fill_price  double precision,
    fill_qty    integer,
    notes       text
);

CREATE INDEX IF NOT EXISTS idx_signal_queue_date_status
    ON public.signal_queue (signal_date, status);

CREATE INDEX IF NOT EXISTS idx_signal_queue_symbol
    ON public.signal_queue (symbol);


-- 3. live_positions — open paper/live positions
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.live_positions (
    symbol          text PRIMARY KEY,
    quantity        integer NOT NULL,
    average_price   double precision NOT NULL,
    entry_date      date NOT NULL,
    strategy        text NOT NULL,
    last_synced_at  timestamp NOT NULL
);


-- 4. decision_logs — per-bar strategy decision audit trail
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.decision_logs (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    timestamp        timestamp NOT NULL,
    symbol           text NOT NULL,
    action           text NOT NULL,
    quantity         double precision,
    price            double precision,
    reasoning        text,
    portfolio_before text,
    portfolio_after  text
);


-- 5. selector_state — AdaptiveStrategySelector persistence (single row, id=1)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.selector_state (
    id               integer PRIMARY KEY DEFAULT 1,
    updated_at       timestamp NOT NULL,
    confirmed_regime text,
    pending_regime   text,
    pending_count    integer NOT NULL DEFAULT 0,
    weights_json     text NOT NULL,
    history_json     text NOT NULL,
    last_rebalanced  date
);

-- Enforce single-row invariant
CREATE UNIQUE INDEX IF NOT EXISTS selector_state_singleton
    ON public.selector_state (id);


-- =============================================================================
-- NOTE: paper_trade_sessions already exists in Supabase B — no action needed.
-- The backend mirror write has been removed; the frontend writes this table
-- directly via the Supabase JS client with the real user JWT.
-- =============================================================================
